@startuml

!define SPRING_GREEN #98FB98

package "Frontend" {
  [UI] #LightBlue
  [React Components] #LightBlue
  [React Router] #LightBlue
  [React Hooks] #LightBlue
}

database "H2/MySQL" as DB

package "Backend" {
  [CourseController] #98FB98
  [ExamController] #98FB98
  [ExamLogController] #98FB98
  [CourseServiceImpl] #98FB98
  [ExamServiceImpl] #98FB98
  [ExamLogServiceImpl] #98FB98
  [CourseRepository] #98FB98
  [ExamRepository] #98FB98
  [ExamLogRepository] #98FB98
}

UI -down-> React_Components: Render
UI --> React_Router: Navigation
UI --> React_Hooks: Manage State

React_Components --> CourseController: HTTP Requests
React_Components --> ExamController: HTTP Requests
React_Components --> ExamLogController: HTTP Requests

CourseController --> CourseServiceImpl: Delegates Actions
ExamController --> ExamServiceImpl: Delegates Actions
ExamLogController --> ExamLogServiceImpl: Delegates Actions

CourseServiceImpl --> CourseRepository: Access Data
ExamServiceImpl --> ExamRepository: Access Data
ExamLogServiceImpl --> ExamLogRepository: Access Data

CourseRepository --> DB: Data Access
ExamRepository --> DB: Data Access
ExamLogRepository --> DB: Data Access

@enduml
