@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class course {
   module_code: varchar(10)
   module_leader: varchar(255)
   module_name: varchar(255)
   registered_students: int
   course_id: bigint
}
class exam {
   end_time: time
   exam_day: date
   start_time: time
   semester: varchar(10)
   exam_year: varchar(4)
   course_id: bigint
   id: bigint
}
class examlogs {
   end_time: time
   message: varchar(255)
   start_time: time
   students_logged: bigint
   submitted_date: date
   venue: varchar(255)
   exam_id: bigint
   id: bigint
}

examlogs  -[#595959,plain]-^  exam     : "exam_id:id"
@enduml
